### ISSUE TITLE
经常排版出现问题

### ISSUE THREAD

**Issue by songcser** [sabrinaluo/hexo-theme-replica#13]
执行 hexo generate后排版出现问题。
![image](https://user-images.githubusercontent.com/3416025/30915042-0c119e76-a3c8-11e7-9fc1-c8e5336983d2.png)

**Comment by sabrinaluo** [comment]
Have you ever generated your site with `replica v1.0`? If so, it might be the cache issue of hexo.

You can try to clear your cached file and regenerate again:
```
hexo clean
hexo g
```

**Comment by songcser** [comment]
OK, thanks
