### ISSUE TITLE
Suggestions for concealing some not completed functions

### ISSUE THREAD

**Issue by VictorZhang2014** [sabrinaluo/hexo-theme-replica#14]
Hello Beauty Programmer,

First, I want to praise you that this theme for HEXO looks stunning and I think you have been spending many time on it. 
But I suppose it would be better if you could conceal those functions which have not been completed.

Thanks.

**Comment by sabrinaluo** [comment]
Can you give more details about the *uncompleted functions*? Sorry I didn't release which are not completed😅

**Comment by VictorZhang2014** [comment]
Take your tech blog site (http://sabrinaluo.com/tech/) for example, the two points aren't completed as follows:
- 1.There are two icons on the top right corner-Notification and Addition respectively.
- 2.In the article details text page, the components of Share, Discussion, Bookmark, and Smaile.

As you mentioned, v1.0 has completed, and v2.0 is in progress. So I should clone v1.0 to my blog site.

**Comment by VictorZhang2014** [comment]
Due to I'm a not a Front-End programmer, so I can't cooperate with you completing this overwhelming theme, sorry for that.

**Comment by sabrinaluo** [comment]
Those are for design purpose only, to make the site looks more like the real github.

**Comment by VictorZhang2014** [comment]
Not only it looks like github, I think it is real github. I confused them in severals time😄
