### ISSUE TITLE
Theme v1.0 happened errors

### ISSUE THREAD

**Issue by VictorZhang2014** [sabrinaluo/hexo-theme-replica#15]
I cloned v1.0 using by `git clone -b v1.0 https://github.com/sabrinaluo/hexo-theme-replica.git themes/replica`.

And I input a command `hexo s` in Terminal and opened `http://localhost:4000/` on the browser.

Finally, It occurred errors 
[
![wechatimg24](https://user-images.githubusercontent.com/6853884/31593195-ce7c41c2-b1f2-11e7-8da9-9915d435a52a.jpeg)
](url)

I'm 😂 
Or I'm just waiting you for completing the v2.0. 💫
Thank you for your contribution. 💖

**Comment by sabrinaluo** [comment]
You will need to put below section into your root `_config.yml`
```
social:
  github: 
  weibo: 
  linkedin: 
```

Better to copy the whole config from README, and remove / replace only the **value** you don't need, and don't remove the key

**Comment by VictorZhang2014** [comment]
![wechatimg1](https://user-images.githubusercontent.com/6853884/31595982-f2569b8a-b204-11e7-9afc-ad67e26af76c.jpeg)
![wechatimg2](https://user-images.githubusercontent.com/6853884/31595983-f2a44114-b204-11e7-938e-841518012f13.jpeg)

It's still throwing errors like photos showing above.

**Comment by sabrinaluo** [comment]
It works on my end. Can you paste your whole `_config.yml` file here if you don't mind

**Comment by VictorZhang2014** [comment]
![wechatimg58](https://user-images.githubusercontent.com/6853884/31621777-38013374-b260-11e7-9b9d-1ae9887b1de7.jpeg)

That's the whole text in the `_config.yml`

**Comment by sabrinaluo** [comment]
I think it's the same issue with https://github.com/sabrinaluo/hexo-theme-replica/issues/10
You will need to have another `_config.yml` in your **root folder**

**Comment by VictorZhang2014** [comment]
Well, I decided to use v2.0. Thank you
