### ISSUE TITLE
文章过多时排版错误

### ISSUE THREAD

**Issue by GreenHatHG** [sabrinaluo/hexo-theme-replica#20]
当我把_post文件删除，然后执行
`hexo clean`
`hexo g`
`hexo s`
浏览器打开显示正确的排版
但是把_post放到正确位置，然后执行
`hexo clean`
`hexo g`
`hexo s`
发现排版就会错误，不知道是不是文章过多导致排版错误
这是`hexo g`输出的结果：
[https://paste.ubuntu.com/p/bPtWV2MkGV/](https://paste.ubuntu.com/p/bPtWV2MkGV/)
`_post`文件夹下文件个数：
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1fzdn85i2sij30gz04u0uk.jpg">
chrome71.0.3578.98无痕模式访问`localhost:4000`：
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1fzdn9mvvkwj311y0hjafy.jpg">
系统配置：
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1fzdnctpgc1j30vb0ibjzn.jpg">

**Comment by sabrinaluo** [comment]
跟文章数量应该没有关系，我的一个博客有58篇，排版是正常的。
我在本地偶尔也会出现排版有问题的情况，但是通过CI部署从来没有出现过（每次都是无缓存环境中执行`npm install`, `hexo g`）。现在还不清楚出现问题的原因，但推测可能是本地存在缓存而导致的。
通常情况下`hexo clean`就可以解决了，如果还不行可以试试手动删除`public`和`db.json`

**Comment by GreenHatHG** [comment]
你好，我手动删除了`public`和`db.json``还是一样问题

**Comment by sabrinaluo** [comment]
是否试过CI部署或者清除缓存后生成public文件夹自己手动部署呢？根据我的经验`hexo g`生成的文件源码css那些都是没有问题的，反而是`hexo s`的时候浏览器里看到的源码有问题

**Comment by GreenHatHG** [comment]
你好，请问CI部署是什么？
我刚刚执行
`sudo rm -r node_modules db.json public`
然后重新安装依赖
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1fzfa1k4gv5j311k0fz7a8.jpg">
然后
`hexo clean`
`hexo g`
`hexo s`
还是不能正常显示

**Comment by sabrinaluo** [comment]
CI continuous integration即是持续集成，通常有Travis, Jenkins等，不用CI也可以，是否试过手动部署public文件夹，也就是不使用hexo s，而是自己搭建一个web server

**Comment by GreenHatHG** [comment]
你好，应该是我本地环境问题 ，我刚刚在一个ubuntu docker容器里面试过了，可以正常显示。
感谢你的回答
