### ISSUE TITLE
你好，分类页和标签页无法使用

### ISSUE THREAD

**Issue by iguanren** [sabrinaluo/hexo-theme-replica#21]
你好，正在使用这款主题，首页和文章页正常，分类和标签页无法使用，该怎么解决呢？地址blog.uycool.com

**Comment by sabrinaluo** [comment]
需要在`source`文件夹下创建`categories`和`tags`文件夹，并添加`index.md`文件

可以参考： https://github.com/sabrinaluo/tech/tree/995beb2fb6450c7b3cbdb37537c366ecb466b6ff/source
