### ISSUE TITLE
CSS IN DISORDER

### ISSUE THREAD

**Issue by GitHubJiKe** [sabrinaluo/hexo-theme-replica#26]
I really like this theme, but when I use it, I found it's css was in disorder. just like this
![image](https://user-images.githubusercontent.com/15058227/54816387-11acf680-4ccf-11e9-9d36-d32037b6a57a.png)
And I tried to fix it in your main.css by copy online code from your blog [小白妹妹写代码](https://sabrinaluo.github.io/),but it's too hard to finish this work, so would you tell me how to fix this issue,.
Thx.

**Comment by GitHubJiKe** [comment]
sorry, I found a way to fix: hexo clean, then hexo g ;hexo s. it's my fault, sorry.

**Comment by sabrinaluo** [comment]
#20 #13
