### ISSUE TITLE
social 图标在fontawesome中不存在怎么处理

### ISSUE THREAD

**Issue by tdouguo** [sabrinaluo/hexo-theme-replica#29]
以此提交为例, twitter,facebook,stackoverflow  中的图标在fontawesome可以搜索到并添加成功了
https://github.com/sabrinaluo/hexo-theme-replica/pull/28/commits/6c4d5724bb214c7144161baebcdb193281ecaec9

但是 csdn,知乎,简书,博客园等 在fontawesome无法搜索到 所以无法添加该链接, 添加后 hexo s 运行失败因为无法找到icon

**Comment by tdouguo** [comment]
找到一个 替换 方案: https://www.jianshu.com/p/5d4a39cdf96d
https://www.iconfont.cn/ 这个 量级很多

未知待验证： 
    1. 是否在全球范围都可以使用

**Comment by sabrinaluo** [comment]
能想到的代替方案为允许添加图片作为icon，判断配置如果符合pattern `//www.example.com/example.jpg` 则直接用img代替font icon，这样更flexible一些
