### ISSUE TITLE
求问 Hexo G 生成问题

### ISSUE THREAD

**Issue by tdouguo** [sabrinaluo/hexo-theme-replica#33]
https://0x96m.com/
类似这样的
我在本地 生成也是这样不知道为什么 也没有报错  主题也有
但是我用另外一个 https://tdou.cc 这个是使用的 https://travis-ci.com/ 生成的 没事  在 windowns 和 pc下都试过了 是我改坏什么东西了吗

**Comment by sabrinaluo** [comment]
may refer to #20

**Comment by tdouguo** [comment]
我尝试过几种方法还是不行
1. hexo clean  hexo g  生成的public下 html  布局异常
2. hexo clean 之后 删除 public 和 db.json 文件 重新生成 布局异常
但是 通过 https://travis-ci.com/ 自动部署的则没有问题
hexo s 也是预览OK状态
