### ISSUE TITLE
可以新增分页功能吗

### ISSUE THREAD

**Issue by harvies** [sabrinaluo/hexo-theme-replica#37]
如题，真心喜欢这个主题，能加分页就完美了

**Comment by sabrinaluo** [comment]
分页的话是指文章列表页吗？github里好像没有类似的设计呢

**Comment by harvies** [comment]
> 分页的话是指文章列表页吗？github里好像没有类似的设计呢

是的 github是下滑刷新  这个项目是一次把所有文章都加载出来了

**Comment by mynameisny** [comment]
我这里也没有看到分页的效果：
“Overview”页面下，只有6篇最近发表的文章，而在“Posts”页面下，只有10篇文章，并没有看到所有文章呢？

**Comment by mynameisny** [comment]
- 修改hexo根目录的_config.yml文件，设置每页显示的数量：
`per_page: 10`

- 新建 _partial/paginator.ejs文件：
```
<% if (page.total > 1){ %>
  <nav class="page-nav">
    <%- paginator({
      prev_text: "Previous",
      next_text: "Next",
	  show_all: false
    }) %>
  </nav>
<% } %>
```

- 编辑/layout/archive.ejs文件，在最后两个div闭合标签前面加入：
  `<%- partial('_partial/paginator') %>`

> 我不会调样式，可以去Github的Star页面抄一个，有点像按钮那样的效果，要是有小伙伴成功了，记得给大家发一下代码吧。

**Comment by mynameisny** [comment]
> 分页的话是指文章列表页吗？github里好像没有类似的设计呢


是有这样的设计的，可能是Github默认显示出来列表项都比较多，所以翻页键可能不经常出现。我Star了很多项目，经常会翻几页才找到想要的。

感谢您的作品，主题好看，人也很漂亮，希望可以帮忙给加一下这个样式呢。蟹蟹！
